version: '3'
services:
  postgres:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: devroot
    networks:
      - backend
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend
  node:
    build:
      context: .
      dockerfile: ./dockerfiles/dockerfile.dev
    container_name: api-mutant
    env_file:
      - .env.local
    networks:
      - backend
    ports:
      - '9229:9229'
      - '3000:3000'
    volumes:
      - .:/usr/app

networks:
  backend:
